### ISSUE TITLE
TLS Handshake failed, But Certificate Trusted

### ISSUE THREAD

**Issue by fr0zenrain** [MegatronKing/NetBare-Android#90]
the failed stacktrace as follows, firstly i think it have releationship with TLSv1.3, but when i do some research, i think it's not.i'm use TLSv1.2 but give a SSLV3_ALERT_HANDSHAKE_FAILURE  error,the certificate was trusted, anyone can give some advice for me,thanks!

javax.net.ssl.SSLHandshakeException: Handshake failed
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:288)
        at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:196)
        at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:153)
        at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
        at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
        at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:262)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:219)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:30)
        at java.lang.reflect.Method.invoke(Native Method)
        at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
        at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:110)
        at LSPHooker_.getOutputStream(Unknown Source:8)
        at com.umeng.commonsdk.statistics.internal.c.b(NetworkHelper.java:40)
        at com.umeng.commonsdk.statistics.internal.c.a(NetworkHelper.java:15)
        at com.umeng.commonsdk.statistics.c.a(NetWorkManager.java:5)
        at com.umeng.commonsdk.framework.b.q(UMNetWorkSender.java:14)
        at com.umeng.commonsdk.framework.b.j(UMNetWorkSender.java:1)
        at com.umeng.commonsdk.framework.b$2.handleMessage(UMNetWorkSender.java:5)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0xe6c76c58: Failure in SSL library, usually a protocol error
    error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE (external/boringssl/src/ssl/tls_record.cc:587 0xd373b348:0x00000001)
    error:1000009a:SSL routines:OPENSSL_internal:HANDSHAKE_FAILURE_ON_CLIENT_HELLO (external/boringssl/src/ssl/handshake.cc:580 0xd3e541c7:0x00000000)
        at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
        at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:387)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:226)

**Comment by fr0zenrain** [comment]
No,you can try this project [TunProxy](https://github.com/raise-isayan/TunProxy)
